version: '3'

services:
  jabref:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REPO_URL=https://github.com/Maryam-Asad19/jabref-checkstyle-docker.git
    volumes:
      - ./report:/app/report